# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
      # Primary container image where all steps run
      - image: gradle:7.3.1-jdk17-alpine
          auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          gradle build